name: time_chart
description: A scrollable time chart.
version: 0.0.1
homepage: https://github.com/jja08111/time_chart

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.1.2
  # Waiting for this PR: https://github.com/nateshmbhat/touchable/pull/17
  #touchable:
  #  git:
  #    url: https://github.com/jja08111/touchable
  path_drawing: ^0.4.1+1
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter